### ISSUE TITLE
Spotlight poster view slow load time when opening a list via addon

### ISSUE THREAD

**Issue by deyooluv** [marduklev/skin.swan-alpha#10]
Please the spotlight poster view takes the longest to load a list. I personally stream through addon. Unlike other views In this skin the sportlight poster(view type 503) takes the longest to load a list from an addon. 
I think the view is making other calls that is slowing the load time.
I was wondering if there is a setting to disable some of the API calls made during the load time to the view can load faster in comparable with other views of the skin.

**Comment by marduklev** [comment]
Hi, again.
I currently not facing some issues for myself.
which does not mean it s perfect on your end.

I do some code cleanup at later stage and maybe it speeds things up on your end.But no Promise.

I'll close this for now as speed penalty can eventually just came in passively due to later cleanup (which is than not issue realted step).
